# Generated by Django 5.2.5 on 2025-08-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Discount Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Discount Type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Order Amount')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Usage (global)')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(verbose_name='Valid Until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_discounts', to='promotions.discount', verbose_name='Discount')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='discounts', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Discount',
                'verbose_name_plural': 'Product Discounts',
            },
        ),
        migrations.CreateModel(
            name='PromocodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Used At')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.promocode', verbose_name='Promo Code')),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
            },
        ),
    ]
